### ISSUE TITLE
Fetch a random photo.

### ISSUE THREAD

**Issue by ghost** [salvoventura/pypexels#3]
I want to be able to access a random photo from the Pexels api.

It says in the documentation (under the random photos heading) to access random photos, you must use the ["curated photos"](https://www.pexels.com/api/documentation) endpoint.

However, looking at the wrapper, I cannot see where this functionality is supported.

**Comment by salvoventura** [comment]
You are correct: that is missing. And I am noticing that the "popular" API endpoint is not documented anymore, which seems to imply the API changed along the way.

Thanks for bringing this up: I'll need to add the "curated" support. Probably will create a "random" endpoint in the library, for convenience. Shouldn't take too long, but it's not trivial.

**Comment by salvoventura** [comment]
"Random photo fetch" is an enhancement. Curated Photos missing is a bug: will open that separately.

**Comment by salvoventura** [comment]
Feature added in master branch. Will get picked up in next official release soon.
