### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by DavidM42** [salvoventura/pypexels#5]
[The api documentation](https://www.pexels.com/videos/) also lists support for features on video clips. I looked through the pypexels documentation and couldn't find any reference to video content. Is anything concerning video planned or not yet?

**Comment by salvoventura** [comment]
Thanks for bringing this up. I have tried those API calls, but they are returning 403 - "Access to this API has been disallowed". I have an open inquiry with the API support team at Pexels before proceeding.

**Comment by DavidM42** [comment]
You're right. That's very strange. I just tried it too and for me the popular videos and search videos api endpoints work as intended but getting a single video via `https://api.pexels.com/v1/videos/videos/:id` produces `{
    "error": "Requested endpoint is forbidden"
}`

**Comment by salvoventura** [comment]
I am still waiting for an answer from the API support team at Pexels. I emailed them again yesterday. If you happen to have a working example, I would like to compare your settings with mine.

**Comment by ricard-inho** [comment]
Do you know if the videos work as today?

**Comment by salvoventura** [comment]
Hello,
 they don't at the moment: I just discovered my testing API KEY has been changed, hence I wasn't able to access video for testing. I have now access. I'll be working on adding video support to the library starting today. Stay tuned for updates, it may take a few days.

Cheers!

**Comment by ricard-inho** [comment]
Sounds great!

**Comment by salvoventura** [comment]
Release 1.0.0rc1 is now available, and has Videos API support.

Cheers!
